# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: movie
